config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root    'static_pages#home'
  get     'static_pages/home'
  get     '/contact',     to: 'contacts#new'
  get     '/about',       to: 'static_pages#about'
  get     '/quick-meme',  to: 'static_pages#quick_meme'
  get     '/signup',      to: 'users#new'
  post    '/signup',      to: 'users#create'
  get     '/login',       to: 'sessions#new'
  post    '/login',       to: 'sessions#create'
  delete  '/logout',      to: 'sessions#destroy'
  resources :contacts,            only: [:new, :create]
  resources :users do
    resources :memes,             only: [:show, :create, :destroy, :update] do
      resources :favorite_memes,      only: [:create, :destroy]
    end
  end
  resources :memes,               only: [:create]
  resources :original_images,     only: [:index, :create, :show, :destroy, :update]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if params[:all]
      redirect_to root_path
    else
      filter = params[:filter]
      if filter == "day" || filter == "week" || filter == "month"
        created_at_statement = ""
        case filter
        when "day"
          created_at_statement = 1.day.ago
        when "week"
          created_at_statement = 7.days.ago
        when "month"
          created_at_statement = 1.month.ago
        end
        @search = Sunspot.search(Meme) do
          fulltext params[:search]
          with(:created_at).greater_than created_at_statement
          with :private, false
          order_by :favorites_count, :desc
          paginate(:page => params[:page] || 1, :per_page => 35)
        end
      else
        @search = Sunspot.search(Meme) do
          fulltext params[:search]
          with :private, false
          order_by :favorites_count, :desc
          paginate(:page => params[:page] || 1, :per_page => 35)
        end
      end
      @query = params[:search]
      @memes = @search.results
    end
    @tag_cloud_memes = Meme.all.order(created_at: :desc).where(private: false)
  end

  def contact
  end
  
  def about
  end
  
  def quick_meme
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About Muh Memes</h1>
<p>Store your favorite memes on your homepage</p>
<p>Tag memes and gifs for easy retrieval</p>
<p>Share memes with friends in your network</p>
<p>Generate new memes with the meme machine</p>

app/views/static_pages/home.html.erb
<% if !current_user %>  
  <div class="center jumbotron header" id="sign-up-header">
    <h1>Muh Memes</h1>
    <p>A community for creating, saving, and sharing memes!</p>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    <br>
    <p id="quick-meme-stmt">Not ready to sign up? Try a <%= link_to "quick meme", quick_meme_path %>!</p>
    <div class="center" id="demo-wrapper">
      <%= image_tag("muh-memes-demo.gif", :alt => "demo", :id => "home-page-demo") %>
    </div>
    
  </div>
<% else %>
  <div class="center jumbotron header">
    <h1>Muh Memes</h1>
  </div>
<% end %>
<div class="row meme-index">
  <div class="col-xs-12 meme-thumbnails center">
    <div class="col-xs-12 center search-area">
      <%= form_tag root_path, :method => :get, class: "form-inline", :autocomplete => :off do %>
        <div class="input-group col-xs-8 col-md-6 col-lg-4 search-bar">
          <%= text_field_tag :search, params[:search], placeholder: "Search All Memes", class: "form-control col-xs-12" %>
        </div>
          <%= button_tag type: "submit", class: "btn btn-secondary" do %>
            <span class="glyphicon glyphicon-search"></span>
          <% end %>
          <%= button_tag type: "submit", class: "btn btn-primary", name: "all" do %>
            <span class="glyphicon glyphicon-refresh"></span>
          <% end %>
      <% end %>
    </div>
    <div id="filters" class="col-sm-12 col-md-offset-2 col-md-8" data-filter=<%= params[:filter] ? params[:filter] : "all-time" %>>
      <%= link_to "Day", { :filter => "day", :search => params[:search] }, :class => "btn btn-primary filter-button", :id => "day-filter" %>
      <%= link_to "Week", { :filter => "week", :search => params[:search] }, :class => "btn btn-primary filter-button", :id => "week-filter" %>
      <%= link_to "Month", { :filter => "month", :search => params[:search] }, :class => "btn btn-primary filter-button", :id => "month-filter" %>
      <%= link_to "All Time", { :filter => "all-time", :search => params[:search] }, :class => "btn btn-primary filter-button", :id => "all-time-filter" %>
    </div>
    <div class="row">
      <div class="tag-cloud col-xs-12 col-md-offset-3 col-md-6">
        <% tag_cloud @tag_cloud_memes.limited_tag_counts, %w[s m l] do |tag, css_class| %>
          <%= link_to tag.name, { :search => tag.name }, class: css_class %>
        <% end %>
      </div>
    </div>
    
    <%= will_paginate @memes %>
    
    <ul class="memes-list">
      <% @memes.each do |meme| %>
        <li id="meme-<%= meme.id %>">  
          <span class="image-thumb"><%= link_to image_tag(meme.image_url(:thumb)), user_meme_path(meme.user, meme) if meme.image? %></span>
        </li>
      <% end %>
    </ul>
    
   <%= will_paginate @memes %>
  </div>
</div>

<script>
  var filter = $("#filters").data('filter');
  if (filter === "day") {
    $("#day-filter").addClass("filter-selected");
  } else if (filter === "week") {
    $("#week-filter").addClass("filter-selected");
  } else if (filter === "month") {
    $("#month-filter").addClass("filter-selected");
  } else {
    $("#all-time-filter").addClass("filter-selected");
  }
</script>

app/views/static_pages/quick_meme.html.erb
<%= provide(:title, "Quick Meme") %>

<div class="row meme-creation">
  <%= render 'shared/meme_form_quick_meme' %>
</div>