config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root    'static_pages#home'
  get     'static_pages/home'
  get     '/contact',     to: 'contacts#new'
  get     '/about',       to: 'static_pages#about'
  get     '/quick-meme',  to: 'static_pages#quick_meme'
  get     '/signup',      to: 'users#new'
  post    '/signup',      to: 'users#create'
  get     '/login',       to: 'sessions#new'
  post    '/login',       to: 'sessions#create'
  delete  '/logout',      to: 'sessions#destroy'
  resources :contacts,            only: [:new, :create]
  resources :users do
    resources :memes,             only: [:show, :create, :destroy, :update] do
      resources :favorite_memes,      only: [:create, :destroy]
    end
  end
  resources :memes,               only: [:create]
  resources :original_images,     only: [:index, :create, :show, :destroy, :update]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
end

app/models/meme.rb
class Meme < ApplicationRecord
  belongs_to :user
  has_one :original_image
  has_many :favorites, as: :favorited
  acts_as_taggable
  mount_base64_uploader :image, ImageUploader
  validates :user_id, presence: true
  validates :image, presence: true
  validate :image_size
  
  searchable do
    integer :id
    text    :tag_list
    integer :user_id
    boolean :private
    time    :created_at
    time    :updated_at
    integer :favorites_count do
      self.favorites.count
    end
  end
  
  def is_public?
    private == false
  end
  
  def self.limited_tag_counts
    self.tag_counts.most_used(50).sort_by{ |item| item.name.downcase }
  end
  
  private
  
    # Validates the size of an uploaded image
    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "should be less than 5MB")
      end
    end
    
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  require 'mini_magick'
  before_action :logged_in_user, only: [:create, :update, :destroy]
  
  def show
    @meme = Meme.find(params[:id])
    if OriginalImage.exists?(id: @meme.original_image_id)
      @original_image = OriginalImage.find(@meme.original_image_id)
      @memes = @original_image.memes.where(private: false).paginate(:page => params[:page], :per_page => 30)
    end
    @user = User.find(@meme.user_id)
    if !current_user?(@user) && @meme.private
      flash[:danger] = "You are not allowed to view private memes!"
      redirect_to root_url
    end
  end
  
  def create
    @user = current_user
    @meme = @user.memes.build(meme_params)
    if !@meme.original_image_id.nil?
      @original_image = OriginalImage.find(@meme.original_image_id)
      params[:meme][:original_image_id] = @original_image.id
    end
    if @meme.save
      flash[:success] = "Meme created!"
    else
      # flash[:danger] = "Meme failed to be created."
      flash[:danger] = "Meme failed to be created. Safari less than 10.1, Internet Explorer less than 11, and Firefox less than 52 are not supported for meme creation."
    end
    redirect_to user_url(current_user)
  end
  
  def update
    @user = User.friendly.find(params[:user_id])
    @meme = @user.memes.find(params[:id])
    
    @meme.assign_attributes(meme_params)
    
    if @meme.save
      respond_to do |format|
        format.html { flash[:success] = "Meme updated!"
                      redirect_to user_url(current_user) }
        format.json
      end
    else
      respond_to do |format|
        format.html { flash[:danger] = "There was an error updating the meme. Please try again."
                      render :show }
        format.json
      end
      
    end
  end
  
  def destroy
    @user = User.friendly.find(params[:user_id])
    @meme = @user.memes.find(params[:id])
    if current_user != @user
      flash[:danger] = "You are not allowed to delete other users' memes!"
      redirect_to user_url(current_user)
    end
    
    if @meme.destroy
      @meme.remove_image!
      flash[:success] = "Meme deleted successfully"
    else
      flash[:danger] = "There was an error deleting the meme"
    end
    redirect_to user_url(current_user)
  end
  
  # Helper method to get tag counts (global)
  def tag_cloud
    @tags = Meme.tag_counts_on(:tags)
  end
  
  private
  
    def meme_params
      params.require(:meme).permit(:image, :remote_image_url, :tag_list, :private, :original_image_id)
    end
    
    def correct_user
      @meme = current_user.memes.find_by(id: params[:id])
      redirect_to root_url if @meme.nil?
    end
    
end

app/helpers/memes_helper.rb
module MemesHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/memes/_meme.html.erb
<li id="meme-<%= meme.id %>">  
  <span class="image-thumb"><%= link_to image_tag(meme.image_url(:thumb)), user_meme_path(@user, meme) if meme.image? %></span>
</li>

app/views/memes/show.html.erb
<%= content_for(:head) do %>
  <%-# Facebook meta tags -%>
  <meta property="og:url" content="/users/<%=@user.id%>/memes/<%=@meme.id%>">
  <meta property="og:type" content="website" />
  <meta property="og:title" content="Muh Memes" />
  <meta property="og:description" content="Create, save, and share awesome memes!" />
  <meta property="og:image" content="<%= @meme.image.url %>" />
  <meta property="og:image:width" content="<%=@meme.image.image_width%>" />
  <meta property="og:image:height" content="<%=@meme.image.image_height%>" />
  <%-# Twitter cards -%>
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:site" content="@ianroberts131" />
  <meta name="twitter:title" content="Muh Memes" />
  <meta name="twitter:description" content="Create, save, and share awesome memes!" />
  <meta name="twitter:image" content="<%= @meme.image.url %>" />
<% end %>

<script>
$(function() {
  $("#meme-private-checkbox-update").change(function() {
    $.ajax({
      type: "PUT",
      url: "/users/<%=@user.id%>/memes/<%=@meme.id%>.json",
      contentType: 'application/json',
      data: JSON.stringify({private: this.checked, _method:"PUT"}),
      dataType: 'json'
      });
  });
});
</script>
<div class="row meme-creation hidden">
  <%= render 'shared/meme_form' %>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3 center">  
    <div class="image">
      <% unless current_user?(@user) %>
      <p>
        Created by: <%= link_to @user.name, user_path(@user) %>
      </p>
      <% end %>
      <p>
        Tags: <%= raw @meme.tag_list.map { |tag| link_to tag, root_path(:search => tag) }.join(", ") %>
      </p>
      <div><%= image_tag(@meme.image.url, :id => "meme-show-image") if @meme.image? %></div>
      <ul class="meme-option-buttons">
        <% if current_user?(@user) %>
          <li id='meme-delete-button' class="col-xs-4 meme-option">
            <%= link_to user_meme_path(@user, @meme), method: :delete do %>
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            <% end %>
          </li>
        <% end %>
        <% if logged_in? %>
          <li class="center meme-option">
            <% if current_user.favorite_memes.exists?(id: @meme.id) %>
              <% favorited = true %>
            <% else %>
              <% favorited = false %>
            <% end %>
            <span class="toggle-favorite" <% if favorited %> style="display: none" <% end %> >
              <%= link_to user_meme_favorite_memes_path(current_user, @meme), method: :post, remote: true  do %>
                <i class="glyphicon glyphicon-heart add-to-favorites-heart"></i>
              <% end %>
            </span>
            <span class="toggle-favorite center" <% unless favorited %> style="display: none" <% end %> >
              <%= link_to user_meme_favorite_meme_path(current_user, @meme), method: :delete, remote: true  do %>
                <i class="glyphicon glyphicon-heart remove-from-favorites-heart"></i>
              <% end %>
            </span>
            <span class="favorites-count"><%= @meme.favorites.count %></span>
          </li>
        <% end %>
        <% if current_user?(@user) %>
          <li class="private-checkbox col-xs-4 meme-option">
            <%= form_for(@meme, url: { controller: "memes", action: "update" }) do |f| %>
              <%= f.check_box :private, class: "check-box", id: "meme-private-checkbox-update" %>
              <%= f.label "private meme" %>
            <% end %>
          </li>
        <% end %>
      </ul>
      <% if @original_image %>
        <button type="button" class="btn btn-success meme-image-button" id="meme-this" data-original-image=<%= @original_image.original_image.url %>>Meme this image!</button>
        <%= link_to "View Original Image", original_image_path(@original_image), :class => "btn btn-primary meme-image-button" %>
      <% end %>
      </div>
      
    <% if current_user?(@user) %>
      <%= form_for(@meme, url: { controller: "memes", action: "update"}, :html => {:class => "form-group"}) do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <div class="col-md-6 col-md-offset-3 center" id="meme-show-tag-section">
        <div class="col-md-12">
          <%= f.label :tag_list, "Update tags (separated by commas)" %>
          <%= f.text_field :tag_list, value: @meme.tag_list.to_s, class: "form-control" %>
        </div>
        <div class="col-md-12">
          <p><%= f.submit "Update tags", class: "btn btn-success" %></p>
        </div>
      </div>
      <% end %>
    <% end %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3 center" id="share-button-container">
        <ul id="share-buttons">
          <li>Share via: </li>
          <li><a href="https://www.facebook.com/sharer/sharer.php?u=
          <%= request.original_url %>" target="_blank" class="meme-show-button"><i class="fa fa-facebook-square fa-lg" aria-hidden="true"></i></a></li>
          <li><a href="http://twitter.com/home?status=
          <%= request.original_url %>" title="Share on Twitter" target="_blank" class="meme-show-button"><i class="fa fa-twitter fa-lg"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="row meme-thumbnails">
  <% if @original_image %>
    <div class="col-xs-12 center">
      <h3>Related Memes (<%= @memes.count %>)</h3>
      <% if @memes.any? %>
        <%= will_paginate @memes %>
        <ul class="memes-list">
          <%= render @memes %>
        </ul>
        <%= will_paginate @memes %>
      <% end %>
    </div>
  <% end %>
</div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>