config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root    'static_pages#home'
  get     'static_pages/home'
  get     '/contact',     to: 'contacts#new'
  get     '/about',       to: 'static_pages#about'
  get     '/quick-meme',  to: 'static_pages#quick_meme'
  get     '/signup',      to: 'users#new'
  post    '/signup',      to: 'users#create'
  get     '/login',       to: 'sessions#new'
  post    '/login',       to: 'sessions#create'
  delete  '/logout',      to: 'sessions#destroy'
  resources :contacts,            only: [:new, :create]
  resources :users do
    resources :memes,             only: [:show, :create, :destroy, :update] do
      resources :favorite_memes,      only: [:create, :destroy]
    end
  end
  resources :memes,               only: [:create]
  resources :original_images,     only: [:index, :create, :show, :destroy, :update]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <nav>
      <div class="pull-left">
        <ul class="nav navbar-nav navbar-left" id="logo-area">
          <li>
            <%= link_to root_path do %>
              <%= image_tag('panda_icon', :alt => "panda", :size => '50x50') %>
            <% end %>
          </li>
          <li><%= link_to "Muh Memes", root_path, id: "logo"%></li>
        </ul>
      </div>
      <div class="pull-right navbar-flexbox-center">
        <div class="navbar-header" id="nav-button">
          <button type="button" class="navbar-toggle navbar-btn" data-toggle="collapse" data-target="#site-links">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="site-links">
          <ul class="nav navbar-nav">
            <li class="header-item"><%= link_to "Home", root_path %></li>
            <li class="header-item"><%= link_to "Image Database", original_images_path %></li>
            <li class="header-item"><%= link_to "Contact", contact_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Create", current_user %></li>
            <% else %>
              <li><%= link_to "Quick Meme", quick_meme_path %></li>
            <% end %>
          </ul>
        </div>
        <div id="profile-dropdown">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <% if current_user.avatar_url(:icon) %>
                    <span class="dropdown-toggle"><%=image_tag(current_user.avatar_url(:icon)) %></span>
                  <% else %>
                    <i class="glyphicon glyphicon-user"></i>
                  <% end %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "My Memes", current_user, class: "dropdown-item" %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Log out", logout_path, method: "delete", class: "dropdown-item" %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:fb="http://ogp.me/ns/fb#">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta charset="utf-8"
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <% if Rails.env.production? %>
      <script type="text/javascript">
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      
        ga('create', 'UA-103620292-1', 'auto');
      </script>
    <% end %>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-2056720549195874",
        enable_page_level_ads: true
      });
    </script>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}", id: "flash") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>